version: '3.4'

services:
  rmt.webapi:
    image: ${DOCKER_REGISTRY-}rmtwebapi
    build:
      context: .
      dockerfile: src/RMT.WebAPI/Dockerfile
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 